---
abstract: 'Pluggable Roles for your controller'
author:
  - 'Dave Houston <dhouston@cpan.org>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.101612, CPAN::Meta::Converter version 2.101610'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: CatalystX-Controller-Pluggable
requires:
  Catalyst::Controller: 0
  Module::Pluggable::Object: 0
  Moose: 0
  Moose::Util: 0
version: 0.02
